baseurl: '/newsman'
google-analytics: 'production'
yandex-metrika: 'production'
include: ['_pages']
exclude: ['README.md', 'node_modules', 'package.json', 'bower_components', 'bower.json', 'gulpfile.js']
includes_dir: ./_components
data_dir: ./_components
