baseurl: '/newsman'
google-analytics: 'production'
yandex-metrika: 'production'
include: ['_pages']
exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json']
includes_dir: ./_components
data_dir: ./_components
