baseurl: ''
permalink: ''
include: ['_pages']
exclude: ['README.md', 'package.json', 'node_modules/', 'bower_components', 'bower.json', 'gulpfile.js']
includes_dir: ./_components
data_dir: ./_components
